### PR TITLE
Source hardening

### PR DESCRIPTION
**Pull request by shaded-enmity**
Hey,

this patchset contains a bunch of code changes to make the code more robust and resilient:
- added safe `strjoin` family of functions
- added `attribute((cleanup))` destructors
- added checks for `strdup` allocation success
- removed `ptr != NULL` checks from `alloca`'d pointers as they are invalid
- replaced `*printf*` family of functions with `strjoin`/`strjoina`
- added a few tests for the common functions

What I have on my radar:
- use prepared statements for database interactions _or_ escape all parameters to queries
- add more `size_t` wrapping checks to the common functions
- handle external processes better
- fix spelling (`tennant` -> `tenant`)

### CODE REVIEW

**Comment by nhorman** [comment]
This looks really good, thanks!  Can I ask you what you've done to test this?  I'd like to make sure we don't break anything before I merge it.

**Comment by shaded-enmity** [comment]
I've checked the builder against the example manifests, now checking the agent as well.

**Comment by nhorman** [comment]
Awesome, thank you!  Please let me know here when you've finished your testing and are satisfied, and I'll merge your branch.

**Comment by shaded-enmity** [comment]
Just a heads up, I'm currently struggling with postgres configuration which hinders the testing, lol :)

**Comment by nhorman** [comment]
understood.  Shouldn't be too hard.  Just open up loopback access for all users in your postgres server, and use the setup scripts in the freight-tools git repo.  I'm in the middle of some btrfs work right now, but as soon as I'm done, I can do some testing too if need be

**Comment by nhorman** [comment]
FWIW, the only setup I did to my db for testing purposes was set the listen address to '*', and add local auth to all databases for all users using the peer method in pg_hba.conf

**Comment by shaded-enmity** [comment]
Since I was working in a VM I was working as root, and that's been causing troubles with the DB creation machinery, this worked:
`sudo -u postgres scripts/createfreightdb.sh fr fu fp fa fw`

I've found at least one regression, will update the branch once I figure out what's going on.

**Comment by nhorman** [comment]
roger that, thanks!  If you want to describe the problem here, I might be able to help you fix it.

**Comment by shaded-enmity** [comment]
Pushed the one regression fix I found so far. I'm going to run some more tests today.

**Comment by nhorman** [comment]
awesome!  Let me know when its ready to review/pull

**Comment by shaded-enmity** [comment]
freight-agent - Install, Uninstall, Exec -- Tested.

**Comment by nhorman** [comment]
sweet, I'll take that as plenty good in this early stage, and will commit.  Thanks for all the work!

**Pull request merged**
